version: '3'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - BROWSER=none
      - WDS_SOCKET_HOST=127.0.0.1
      - WDS_SOCKET_PORT=3000
    # Run as node user
    user: "node"